AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Serverless Spring API - com.relaximus.example::spring-lambda
Globals:
  Api:
    EndpointConfiguration: REGIONAL

Resources:
  SpringLambdaAPI:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Variables:
        webhookUrl: !Sub '${SpringLambdaAPI}.execute-api.${AWS::Region}.amazonaws.com/Prod/ping'

  SpringLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.relaximus.example.StreamLambdaHandler::handleRequest
      Runtime: java8
      CodeUri: target/spring-lambda-1.0-SNAPSHOT-lambda-package.zip
      MemorySize: 512
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 15
      Events:
        GetResource:
          Type: Api
          Properties:
            RestApiId: !Ref SpringLambdaAPI
            Path: /{proxy+}
            Method: any

Outputs:
  SpringLambdaApi:
    Description: URL for application
    Value: !Sub 'https://${SpringLambdaAPI}.execute-api.${AWS::Region}.amazonaws.com/Prod/ping'
    Export:
      Name: SpringLambdaApi
